/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sewatanahmakam.form;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sewatanahmakam.SewaTanahMakam;
import sewatanahmakam.controller.BlokMakamController;
import sewatanahmakam.controller.DataArsipController;
import sewatanahmakam.controller.IdJenazahController;
import sewatanahmakam.controller.IdWarisController;
import sewatanahmakam.controller.TransaksiController;
import sewatanahmakam.data.Blokmakam;
import sewatanahmakam.data.Dataarsip;
import sewatanahmakam.data.Datatransaksi;
import sewatanahmakam.data.Identitasjenazah;
import sewatanahmakam.data.Identitaswaris;

/**
 *
 * @author Candi-PC
 */
public class FormPerpanjangan extends javax.swing.JInternalFrame implements NavigatorFormInterface{

    IdJenazahController jCont=new IdJenazahController(SewaTanahMakam.emf);
    IdWarisController wCont=new IdWarisController(SewaTanahMakam.emf);
    BlokMakamController bCont=new BlokMakamController(SewaTanahMakam.emf);
    TransaksiController tCont=new TransaksiController(SewaTanahMakam.emf);
    DataArsipController aCont=new DataArsipController(SewaTanahMakam.emf);
    Blokmakam blok=new Blokmakam();
    Dataarsip arsip=new Dataarsip();
    Datatransaksi transaksi=new Datatransaksi();
    Identitasjenazah jenazah =new Identitasjenazah();
    Identitaswaris waris=new Identitaswaris();
    DefaultTableModel model;
    public String ars, kdJen, kdWar, kdBlok;
    Calendar tglBaru, tglBerlaku;
    /** 
     * Creates new form FormPerpanjangan 
     */
    public FormPerpanjangan() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(null);
    }
    
    public void pilihArsip(){
        PopArsip PP=new PopArsip();
        PP.FP=this;
        arsip=aCont.findArsip(ars);
        jenazah=jCont.findJenazah(kdJen);
        waris=wCont.findWaris(kdWar);
        blok=bCont.findBlokMakam(kdBlok);
        SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("In-ID"));
        txtNoArsip.setText(ars);
        txtTglBuat.setText(sdf.format(arsip.getTanggalBuatIzin()));
        txtTglHabis.setText(sdf.format(arsip.getTanggalHabisIzin()));
        txtNoWaris.setText(kdWar);
        txtNmWaris.setText(waris.getNamaWaris());
        txtKelaminWAris.setText(waris.getJenisKelamin());
        txtTglLahirWaris.setText(sdf.format(waris.getTanggalLahir()));
        txtAlamatWaris.setText(waris.getAlamat());
        txtNoJenazah.setText(kdJen);
        txtNmJenazah.setText(jenazah.getNamaJenazah());
        txtTglLahirJEnazah.setText(sdf.format(jenazah.getTanggalLahir()));
        txtKElaminJEnazah.setText(jenazah.getJenisKelamin());
        txtAlamat.setText(jenazah.getAlamat());
        txtNoBlok.setText(blok.getKodeBlok());
        txtNamaBLok.setText(blok.getNamaBlok());
        txtKAtegori.setText(blok.getKategori());
        txtLokasi.setText(blok.getLokasi());
        txtHArgaSewa.setText(String.valueOf(blok.getHargaSewa()));
        tglBaru();
        tglMassaBerlaku();
    }
    
    private void tglBaru(){
        //membuat format waktu jam, hari bulan dan tahun dengan locale indonesia
        SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("in-ID"));
        tglBaru=Calendar.getInstance();
        txtTglBaru.setText(sdf.format(tglBaru.getTime()));
    }
    
    private void tglMassaBerlaku(){
        tglBerlaku=Calendar.getInstance();
        tglBerlaku.setTime(new Date());
        tglBerlaku.add(Calendar.YEAR, 3);
        SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("in-ID"));
        txtMassaBerlaku.setText(sdf.format(tglBerlaku.getTime()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNoArsip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTglBuat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTglHabis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNoWaris = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNmWaris = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtKelaminWAris = new javax.swing.JTextField();
        txtTglLahirWaris = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamatWaris = new javax.swing.JTextArea();
        txtKElaminJEnazah = new javax.swing.JTextField();
        txtTglLahirJEnazah = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNoJenazah = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtNmJenazah = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNoBlok = new javax.swing.JTextField();
        txtKAtegori = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNamaBLok = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtHArgaSewa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        btArsip = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btPerpanjangan = new javax.swing.JButton();
        txtTglBaru = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtMassaBerlaku = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(30, 49, 92));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel2.setText("No. Arsip");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        txtNoArsip.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtNoArsip.setBorder(null);
        txtNoArsip.setOpaque(false);
        jPanel1.add(txtNoArsip, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 250, -1));

        jLabel3.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel3.setText("Tanggal Buat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        txtTglBuat.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtTglBuat.setBorder(null);
        txtTglBuat.setOpaque(false);
        jPanel1.add(txtTglBuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 250, -1));

        jLabel4.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Habis");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        txtTglHabis.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtTglHabis.setBorder(null);
        txtTglHabis.setOpaque(false);
        jPanel1.add(txtTglHabis, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 250, -1));

        jLabel5.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel5.setText("No. Waris");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtNoWaris.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtNoWaris.setBorder(null);
        txtNoWaris.setOpaque(false);
        jPanel1.add(txtNoWaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 240, -1));

        jLabel6.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel6.setText("Nama Waris");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtNmWaris.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtNmWaris.setBorder(null);
        txtNmWaris.setOpaque(false);
        jPanel1.add(txtNmWaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 240, -1));

        jLabel7.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Kelamin");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtKelaminWAris.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtKelaminWAris.setBorder(null);
        txtKelaminWAris.setOpaque(false);
        jPanel1.add(txtKelaminWAris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, -1));

        txtTglLahirWaris.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtTglLahirWaris.setBorder(null);
        txtTglLahirWaris.setOpaque(false);
        jPanel1.add(txtTglLahirWaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 240, -1));

        jLabel8.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal Lahir");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel9.setText("Alamat");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        txtAlamatWaris.setColumns(20);
        txtAlamatWaris.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtAlamatWaris.setRows(5);
        jScrollPane1.setViewportView(txtAlamatWaris);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        txtKElaminJEnazah.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtKElaminJEnazah.setBorder(null);
        txtKElaminJEnazah.setOpaque(false);
        jPanel1.add(txtKElaminJEnazah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 240, -1));

        txtTglLahirJEnazah.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtTglLahirJEnazah.setBorder(null);
        txtTglLahirJEnazah.setOpaque(false);
        jPanel1.add(txtTglLahirJEnazah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 240, -1));

        jLabel10.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel10.setText("Tanggal Lahir");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel11.setText("No. Jenazah");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        txtNoJenazah.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtNoJenazah.setBorder(null);
        txtNoJenazah.setOpaque(false);
        jPanel1.add(txtNoJenazah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 240, -1));

        jLabel12.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel12.setText("Nama Jenazah");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        txtNmJenazah.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtNmJenazah.setBorder(null);
        txtNmJenazah.setOpaque(false);
        jPanel1.add(txtNmJenazah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 240, -1));

        jLabel13.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel13.setText("Jenis Kelamin");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel14.setText("No. Blok");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        txtNoBlok.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtNoBlok.setBorder(null);
        txtNoBlok.setOpaque(false);
        jPanel1.add(txtNoBlok, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 240, -1));

        txtKAtegori.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtKAtegori.setBorder(null);
        txtKAtegori.setOpaque(false);
        jPanel1.add(txtKAtegori, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 240, -1));

        jLabel15.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel15.setText("Kategori");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

        txtNamaBLok.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtNamaBLok.setBorder(null);
        txtNamaBLok.setOpaque(false);
        jPanel1.add(txtNamaBLok, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 240, -1));

        jLabel16.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel16.setText("Nama Blok");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, -1, -1));

        txtLokasi.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtLokasi.setBorder(null);
        txtLokasi.setOpaque(false);
        jPanel1.add(txtLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 240, -1));

        jLabel17.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel17.setText("Lokasi");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        txtHArgaSewa.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        txtHArgaSewa.setBorder(null);
        txtHArgaSewa.setOpaque(false);
        jPanel1.add(txtHArgaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, 240, -1));

        jLabel18.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel18.setText("Harga Sewa");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, -1, -1));

        jLabel19.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel19.setText("Alamat");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1100, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 250, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 250, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 240, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 240, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 240, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 240, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 240, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 240, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 240, 10));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 240, 10));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 240, 10));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 240, 10));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 240, 10));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 240, 10));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 240, 10));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 250, 10));

        jPanel6.setBackground(new java.awt.Color(106, 117, 146));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btArsip.setBackground(new java.awt.Color(255, 255, 255));
        btArsip.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        btArsip.setText("Arsip");
        btArsip.setOpaque(false);
        btArsip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArsipActionPerformed(evt);
            }
        });
        jPanel6.add(btArsip, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 180, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buka Data Arsip");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel3.setBackground(new java.awt.Color(106, 117, 146));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Perpanjang massa berlaku arsip");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        btPerpanjangan.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        btPerpanjangan.setText("Perpanjang");
        btPerpanjangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPerpanjanganActionPerformed(evt);
            }
        });
        jPanel3.add(btPerpanjangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 181, -1));

        txtTglBaru.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        txtTglBaru.setForeground(new java.awt.Color(255, 255, 255));
        txtTglBaru.setText("Tanggal  baru");
        jPanel3.add(txtTglBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel22.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("hingga");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        txtMassaBerlaku.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        txtMassaBerlaku.setForeground(new java.awt.Color(255, 255, 255));
        txtMassaBerlaku.setText("Masa berlaku");
        jPanel3.add(txtMassaBerlaku, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btArsipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArsipActionPerformed
        PopArsip.getObj().FP=this;
        PopArsip.getObj().setVisible(true);
    }//GEN-LAST:event_btArsipActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        txtNoArsip.setEnabled(false);
        txtTglBuat.setEnabled(false);
        txtTglHabis.setEnabled(false);
        txtNoWaris.setEnabled(false);
        txtNmWaris.setEnabled(false);
        txtKelaminWAris.setEnabled(false);
        txtTglLahirWaris.setEnabled(false);
        txtAlamatWaris.setEnabled(false);
        txtNoJenazah.setEnabled(false);
        txtNmJenazah.setEnabled(false);
        txtKElaminJEnazah.setEnabled(false);
        txtTglLahirJEnazah.setEnabled(false);
        txtAlamat.setEnabled(false);
        txtNoBlok.setEnabled(false);
        txtKAtegori.setEnabled(false);
        txtNamaBLok.setEnabled(false);
        txtLokasi.setEnabled(false);
        txtHArgaSewa.setEnabled(false);
        btArsip.setEnabled(false);
        btPerpanjangan.setEnabled(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void btPerpanjanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPerpanjanganActionPerformed
        simpan();
    }//GEN-LAST:event_btPerpanjanganActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArsip;
    private javax.swing.JButton btPerpanjangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextArea txtAlamatWaris;
    private javax.swing.JTextField txtHArgaSewa;
    private javax.swing.JTextField txtKAtegori;
    private javax.swing.JTextField txtKElaminJEnazah;
    private javax.swing.JTextField txtKelaminWAris;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JLabel txtMassaBerlaku;
    private javax.swing.JTextField txtNamaBLok;
    private javax.swing.JTextField txtNmJenazah;
    private javax.swing.JTextField txtNmWaris;
    private javax.swing.JTextField txtNoArsip;
    private javax.swing.JTextField txtNoBlok;
    private javax.swing.JTextField txtNoJenazah;
    private javax.swing.JTextField txtNoWaris;
    private javax.swing.JLabel txtTglBaru;
    private javax.swing.JTextField txtTglBuat;
    private javax.swing.JTextField txtTglHabis;
    private javax.swing.JTextField txtTglLahirJEnazah;
    private javax.swing.JTextField txtTglLahirWaris;
    // End of variables declaration//GEN-END:variables

    @Override
    public void aktif() {
        btArsip.setEnabled(true);
        btPerpanjangan.setEnabled(true);
    }

    @Override
    public void bersih() {
        txtNoArsip.setText("");
        txtTglBuat.setText("");
        txtTglHabis.setText("");
        txtNoWaris.setText("");
        txtNmWaris.setText("");
        txtKelaminWAris.setText("");
        txtTglLahirWaris.setText("");
        txtAlamatWaris.setText("");
        txtNoJenazah.setText("");
        txtNmJenazah.setText("");
        txtKElaminJEnazah.setText("");
        txtTglLahirJEnazah.setText("");
        txtAlamat.setText("");
        txtNoBlok.setText("");
        txtKAtegori.setText("");
        txtNamaBLok.setText("");
        txtLokasi.setText("");
        txtHArgaSewa.setText("");
        txtTglBaru.setText("Tanggal baru");
        txtMassaBerlaku.setText("Massa berlaku");
    }

    @Override
    public void simpan() {
        if("".equals(txtNoArsip.getText())){
            JOptionPane.showMessageDialog(null, "Pilih Arsip!");
        }else{
            try{
                System.out.println(tglBerlaku.getTime());
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd", Locale.forLanguageTag("in-ID"));
                System.out.println(ars);
                String tgl=sdf.format(tglBerlaku.getTime());
                System.out.println(tgl);
                aCont.updateIzin(ars, tgl);
                System.out.println(ars);
                
            }catch(Exception ex){}
            JOptionPane.showMessageDialog(null, "Arsip berhasil diperpanjang!");
            bersih();
        }
    }

    @Override
    public void hapus() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cari() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void tampil() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
